blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/mnichols08/drawer-count-app/security/advisories/new
    about: Please report security vulnerabilities privately via GitHub Security Advisories.
  - name: Questions and support
    url: https://github.com/mnichols08/drawer-count-app/discussions
    about: Please ask and answer questions here.
