name: CI

on:
  pull_request:
    branches: [ development, main ]
  push:
    branches: [ development ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Lint JavaScript
        run: |
          npx eslint . --ext .js || true

      - name: Lint Markdown
        run: |
          npx markdownlint "**/*.md" --ignore node_modules --ignore dist || true
