name: CI

on:
  pull_request:
    branches: [ development, main ]
  push:
    branches: [ development ]
  workflow_dispatch:
    inputs:
      run_full_tests:
        description: 'Run full test suite including E2E'
        required: false
        default: false
        type: boolean

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests (skip E2E by default)
        run: cross-env DCA_SKIP_FULL_TEST=1 node tests/run-tests.js

      - name: Run E2E tests (only if requested or on PR)
        if: github.event.inputs.run_full_tests == 'true' || github.event_name == 'pull_request'
        run: |
          npx playwright install --with-deps
          npm run test:e2e

      - name: Lint JavaScript
        run: npm run lint:js

      - name: Lint Markdown
        run: npm run lint:md
