name: Quick CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'CHANGELOG.md'
      - 'LICENSE'
  workflow_dispatch:

# Allow only one concurrent deployment
concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Quick lint check
        run: npm run lint:js

      - name: Build check
        run: npm run build

      - name: Basic unit tests only (skip E2E)
        run: cross-env DCA_SKIP_FULL_TEST=1 node tests/run-tests.js